<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>SB Admin - Login</title>

   

  </head>

  <body class="bg-dark">

    <div class="container">
      <div class="card card-login mx-auto mt-5">
        <div class="card-header">后台系统登录</div>
        <div class="card-body">
         
            <?=$this->tag->form('login/login') ?>
          <input type="hidden" name="<?php echo $this->security->getTokenKey() ?>"
        value="<?php echo $this->security->getToken() ?>"/>
<div class="form-group">
    <div class="form-label-group">
         
    <?= $this->tag->textField(
      array(
        'name'=>'username',
        'class'=>'form-control',
        'id'=>'username',
        'placeholder'=>'用户名',
        'required'=>'required',
        'onfocus'=>'disableAlert()'
      )
    ) ?> 
    <label for="username">用户名:</label>
</div>
</div>
<div class="form-group">
<div class="form-label-group">
          
    <?= $this->tag->passwordField(array(
      'name'=>'password',
      'class'=>"form-control",
      'id'=>'password',
      'placeholder'=>"密码",
      'required'=>"required",
      'onfocus'=>'disableAlert()'

    )) ?>
    <label for="password">密码:</label>
  </div>
</div>

<?=$this->flashSession->output()?>
    <?= $this->tag->submitButton(
      array(
        "登录",
        'class'=>'btn btn-primary btn-block'

      )
) ?>
 <?= $this->tag->endForm() ?>
 
        </div>
      </div>
    </div>


  </body>

</html>

<script>
 document.getElementsByClassName('errorMessage')[0].classList.add("alert","alert-danger");
function disableAlert(){
x= document.getElementsByClassName('errorMessage')[0];
x.parentNode.removeChild(x);
}
</script>
